# Generated by Django 4.2.7 on 2023-11-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_profile_image',
        ),
    ]
